In [1]:
from matplotlib.colors import ListedColormap
from sklearn import cross_validation, datasets, metrics, tree 

import numpy as np

C:\Users\ddare\Anaconda3\envs\TWO\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data_set=datasets.load_digits(return_X_y=True)

In [7]:
print(data_set[0])

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [10]:
X=data_set[0]
y=data_set[1]

In [46]:
y.shape
len(y)

1797

In [16]:
from sklearn.cross_validation import train_test_split

(X_train, 
 X_test, 
 y_train, y_test) = train_test_split(X, y, 
                                     test_size=0.3, 
                                     random_state=0)

In [28]:
print(X_test)

[[ 0.  0. 11. ... 13. 16.  8.]
 [ 0.  1. 15. ...  1.  0.  0.]
 [ 0.  2. 13. ... 16. 16.  3.]
 ...
 [ 0.  0.  0. ... 15.  1.  0.]
 [ 0.  0.  8. ...  2.  0.  0.]
 [ 0.  0.  1. ... 11.  1.  0.]]


In [20]:
clf = tree.DecisionTreeClassifier(random_state=1)
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')

In [25]:
from sklearn.cross_validation import cross_val_score

In [31]:
predictions = clf.predict(X_test)

In [33]:
cross_val_score(clf,X,y,cv=10).mean()

0.8308624439503834

In [35]:
from sklearn.ensemble import BaggingClassifier

C:\Users\ddare\Anaconda3\envs\TWO\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [36]:
clf2=BaggingClassifier(clf,n_estimators = 100)

In [37]:
clf2.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [38]:
predictions2 = clf2.predict(X_test)

In [39]:
cross_val_score(clf2,X,y,cv=10).mean()

0.9249342507408361

In [44]:
import math

In [47]:
max_featureSQ = math.sqrt(len(y))

In [56]:
clf22 = tree.DecisionTreeClassifier(random_state=1,max_features=42)

In [57]:
clf3=BaggingClassifier(clf22,n_estimators = 100)

In [58]:
clf3.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=42, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [59]:
predictions3 = clf3.predict(X_test)

In [60]:
cross_val_score(clf3,X,y,cv=10).mean()

0.9377571810884258

In [63]:
clf44 = tree.DecisionTreeClassifier(random_state=1,max_features=42,splitter="random")

In [64]:
clf4=BaggingClassifier(clf44,n_estimators = 100)

In [65]:
clf4.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=42, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='random'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [66]:
predictions4 = clf4.predict(X_test)

In [67]:
cross_val_score(clf4,X,y,cv=10).mean()

0.9538786146902416

# Задание 5

In [79]:
from sklearn import ensemble

In [116]:
rf = ensemble.RandomForestClassifier(n_estimators = 100,max_features=5, random_state = 1)

In [117]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=5, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [118]:
predictions4 = rf.predict(X_test)

In [119]:
cross_val_score(rf,X,y,cv=10).mean()

0.9566569519420097